import streamlit as st
import datetime
import re 

# --- CORE LOGIC (The Engine) ---
def process_notes(raw_text, tone, user_name="Pavan", mask_data=True):
    # Apply masking first if requested
    if mask_data:
        raw_text = apply_data_masking(raw_text)
    
    # 1. Action Item Extraction Logic
    triggers = ["needs to", "should", "must", "action:", "fix", "task:", "update", "draft"]
    sentences = raw_text.split('.')
    action_items = [s.strip() for s in sentences if any(t in s.lower() for t in triggers)]
    
    # 2. Executive Summary Generation
    summary = sentences[0].strip() + "." if sentences else "No notes provided."
    
    # 3. Tone Customization Logic
    if tone == "Formal":
        header = f"Dear Team,\n\nFollowing our latest discussion, here is the executive summary and the required next steps."
        sign_off = "Best regards,\nProject Management Office"
    else:
        header = f"Hey everyone! 👋\n\nJust dropping the notes from our chat. Here’s what we need to crush:"
        sign_off = "Let's get it done!\n- AI Ops Bot"

    # 4. Formatting Consistency (The Final Report)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    report = f"{header}\n\n"
    report += f"📍 SUMMARY: {summary}\n\n"
    report += "✅ ACTION ITEMS:\n"
    for item in action_items:
        report += f"• {item}\n"
    report += f"\n{sign_off}"
    report += f"\n\n---\nGenerated by SmartComms AI | {timestamp}"
    
    return report
def apply_data_masking(text):
    # 1. Mask Email Addresses
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '[EMAIL_REDACTED]', text)
    
    # 2. Mask Phone Numbers (Standard 10-digit formats)
    text = re.sub(r'\b\d{3}[-.\s]??\d{3}[-.\s]??\d{4}\b', '[PHONE_REDACTED]', text)
    
    # 3. Mask Potential Budget/Financial Figures (Simple $ logic)
    text = re.sub(r'\$\d+(?:,\d{3})*(?:\.\d{2})?', '[FINANCIAL_DATA_REDACTED]', text)
    
    return text


# --- UI LAYER (The Dashboard) ---
st.set_page_config(page_title="Internal AI Tool", page_icon="🚀")

st.title("🚀 SmartComms Executive Dashboard")
st.markdown("Convert messy meeting notes into professional reports and email drafts instantly.")

# Layout: Sidebar for settings
st.sidebar.header("Configuration")
user_tone = st.sidebar.selectbox("Select Email Tone", ["Formal", "Casual"])
st.sidebar.header("Security Settings")
privacy_mode = st.sidebar.checkbox("Enable Data Masking (Privacy Mode)", value=True)
st.sidebar.info("This tool uses the Company-standard Extraction Logic v1.2")

# Layout: Main Input area
raw_input = st.text_area("📥 Paste Raw Meeting Notes here:", height=150, 
                         placeholder="Example: Meeting with Client. Pavan needs to fix the login bug. We must ship by Friday.")

if st.button("Generate Professional Output"):
    if raw_input:
        with st.spinner('Processing with AI logic...'):
            final_output = process_notes(raw_input, user_tone, mask_data=privacy_mode)
            
            st.subheader("📋 Final Result")
            st.text_area("Secure Output:", value=final_output, height=300)
            
            # Download button for "Executive Summary Generation"
            st.download_button("Download Structured Report", final_output, file_name="meeting_summary.txt")
    else:
        st.warning("Please enter some notes first!")