import datetime

def smart_comms_processor(raw_notes, user_name="Pavan"):
    # 1. Improved Trigger Keywords
    triggers = ["needs to", "should", "must", "action:", "fix", "task:"]
    
    sentences = raw_notes.split('.')
    action_items = []
    
    # 2. Logic to catch tasks
    for s in sentences:
        clean_s = s.strip()
        if any(word in clean_s.lower() for word in triggers):
            action_items.append(clean_s)

    # 3. Generating a Professional Footer (Company Policy)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    footer = f"\n\n---\nGenerated by SmartComms AI | Internal Use Only | {timestamp}"

    # 4. Constructing the Output
    report = f"EXECUTIVE SUMMARY:\nNotes processed for {user_name}.\n"
    report += "TASKS FOUND:\n" + "\n".join([f"• {item}" for item in action_items])
    report += footer

    return report

# TEST DATA
raw_data = "Meeting with the Dev Team. We must finish the API by Tuesday. Pavan needs to check the server logs. We should update the documentation."

print(smart_comms_processor(raw_data))